#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# zsh github completions (https://github.com/zsh-users/zsh-completions)
fpath=(usr/local/share/zsh-completions/src $fpath)

# Use asdf version manager
. /usr/local/opt/asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)

# ensure zsh completions for homebrew packages is enabled
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# zsh github completions (https://github.com/zsh-users/zsh-completions)
fpath=(usr/local/share/zsh-completions/src $fpath)

# Aliases
alias up="../"
alias up2="../../"
alias up3="../../../"
alias dk="docker"
alias g="hub"
alias gpr="hub pull --rebase"
alias be="bundle exec"
